# Generated by Django 5.2.1 on 2025-11-15 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rfid_uid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('plate_number', models.CharField(max_length=20)),
                ('unit_number', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('drivers_license', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('purpose', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied')], max_length=10)),
                ('type', models.CharField(choices=[('OWNED', 'Owned'), ('RENTED', 'Rented'), ('PWD', 'PWD'), ('FREE', 'Free Parking'), ('OPEN', 'Open')], default='OPEN', max_length=10)),
                ('location', models.CharField(blank=True, choices=[('BUILDING_A', 'Building A'), ('BUILDING_B', 'Building B'), ('BUILDING_C', 'Building C'), ('BUILDING_D', 'Building D'), ('BUILDING_E', 'Building E'), ('BUILDING_F', 'Building F'), ('BUILDING_G', 'Building G'), ('ADMIN', 'Admin')], max_length=20, null=True)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.resident')),
            ],
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=10)),
                ('type', models.CharField(choices=[('RESIDENT', 'Resident'), ('VISITOR', 'Visitor')], max_length=10)),
                ('parking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.parkingslot')),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.resident')),
                ('visitor_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.visitor')),
            ],
        ),
    ]
