# Generated by Django 5.2.1 on 2025-11-15 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parkingslot',
            old_name='resident',
            new_name='owner',
        ),
    ]
