# Generated by Django 5.2.1 on 2025-11-26 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='parking_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.parkingslot'),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_owned', to='access_control.resident'),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied')], default='AVAILABLE', max_length=10),
        ),
        migrations.AlterField(
            model_name='rfid',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_issued', to='access_control.resident'),
        ),
    ]
