# Generated by Django 5.2.1 on 2025-11-26 07:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_resident_parking_slot_alter_parkingslot_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='parking_slot',
            field=models.ForeignKey(blank=True, help_text='Select only FREE parking slots', limit_choices_to={'type': 'FREE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.parkingslot'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='rfid',
            field=models.ForeignKey(blank=True, help_text='Select only temporary RFID tags', limit_choices_to={'is_temporary': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.rfid'),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_owned', to='access_control.resident'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='parking_slot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.parkingslot'),
        ),
    ]
