# Generated by Django 5.2.1 on 2025-07-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_rename_parkingspot_parkingslot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parkingslot',
            name='type',
            field=models.CharField(choices=[('OWNED', 'Owned'), ('RENTED', 'Rented'), ('PWD', 'PWD'), ('FREE', 'Free Parking'), ('OPEN', 'Open')], default='OPEN', max_length=10),
        ),
    ]
