# Generated by Django 5.2.1 on 2025-11-26 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_visitor_parking_slot_visitor_rfid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingslot',
            name='owner',
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_slots', to='access_control.resident'),
        ),
        migrations.AddField(
            model_name='parkingslot',
            name='temporary_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_temp', to='access_control.visitor'),
        ),
        migrations.AddField(
            model_name='rfid',
            name='temporary_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfids_temp', to='access_control.visitor'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='parking_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_assigned', to='access_control.parkingslot'),
        ),
        migrations.AlterField(
            model_name='resident',
            name='rfid_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_assigned', to='access_control.rfid'),
        ),
        migrations.AlterField(
            model_name='rfid',
            name='issued_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfids', to='access_control.resident'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='parking_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_temp', to='access_control.parkingslot'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='rfid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='access_control.rfid'),
        ),
    ]
