# Generated by Django 5.2.1 on 2025-07-19 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_parkingslot_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslot',
            name='location',
            field=models.CharField(blank=True, choices=[('BUILDING_A', 'Building A'), ('BUILDING_B', 'Building B'), ('BUILDING_C', 'Building C'), ('BUILDING_D', 'Building D'), ('BUILDING_E', 'Building E'), ('BUILDING_F', 'Building F'), ('BUILDING_G', 'Building G'), ('ADMIN', 'Admin')], max_length=20, null=True),
        ),
    ]
