# Generated by Django 5.2.1 on 2025-12-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0004_remove_parkingslot_owner_parkingslot_issued_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='signed_out',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='visitor',
            name='signed_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
