# Generated by Django 5.2.1 on 2025-12-11 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_visitor_signed_out_visitor_signed_out_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='parking_slot',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='rfid_uid',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='parking_slot',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='rfid',
        ),
    ]
