# Generated by Django 5.2.1 on 2025-10-24 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0005_alter_parkingslot_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('issued_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='resident',
            name='rfid_uid',
        ),
        migrations.AddField(
            model_name='resident',
            name='rfid_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='access_control.rfidtag'),
        ),
    ]
