# Generated by Django 5.2.1 on 2025-11-14 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_rfidtag_remove_resident_rfid_uid_resident_rfid_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='parking_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents_parking_slot', to='access_control.parkingslot'),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_slot_reverse', to='access_control.resident'),
        ),
    ]
