# Generated by Django 5.2.1 on 2025-12-11 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0006_remove_resident_parking_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='parking_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_assigned', to='access_control.parkingslot'),
        ),
        migrations.AddField(
            model_name='resident',
            name='rfid_uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_assigned', to='access_control.rfid'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='parking_slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors_temp', to='access_control.parkingslot'),
        ),
        migrations.AddField(
            model_name='visitor',
            name='rfid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to='access_control.rfid'),
        ),
    ]
