# Generated by Django 5.2.1 on 2025-11-15 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_resident_parking_slot_alter_parkingslot_resident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='rfid_tag',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='parking_slot',
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parking_slots', to='access_control.resident'),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('OCCUPIED', 'Occupied')], default='AVAILABLE', max_length=10),
        ),
        migrations.CreateModel(
            name='RFIDCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('is_temporary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_card', to='access_control.resident')),
                ('visitor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_card', to='access_control.visitor')),
            ],
        ),
        migrations.DeleteModel(
            name='RFIDTag',
        ),
    ]
