# Generated by Django 5.2.1 on 2025-11-14 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_resident_parking_slot_alter_parkingslot_resident'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='rfid_tag',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='parking_slot',
        ),
        migrations.AddField(
            model_name='resident',
            name='rfid_uid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='resident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_control.resident'),
        ),
        migrations.DeleteModel(
            name='RFIDTag',
        ),
    ]
