# Generated by Django 5.2.1 on 2025-12-11 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0007_resident_parking_slot_resident_rfid_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='parking_slot',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='rfid_uid',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='parking_slot',
        ),
        migrations.RemoveField(
            model_name='visitor',
            name='rfid',
        ),
    ]
